name: Build & Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22.20.0
        uses: actions/setup-node@v3
        with:
          node-version: '22.20.0'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build -- --configuration production

      - name: Prepare Deployment Package
        run: |
          rm -rf dist-to-deploy
          mkdir dist-to-deploy
          # Angular Build
          cp -r dist/browser dist-to-deploy/frontend
          # Node.js Backend
          cp -r server.js package.json package-lock.json dist-to-deploy/
          cd dist-to-deploy && zip -r ../app.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-package
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-package
          path: .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
            application_name: "rocci-aws-app"
            environment_name: "rocci-aws-env"
            region: eu-central-1a
            version_label: ${{ github.sha }}
            deployment_package: "app.zip"
