name: Test Workflow
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "✅ GitHub Actions läuft auf Branch ${{ github.ref }}"
